//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMTool.Properties {
    using System;
    using System.Configuration;
    using System.IO;
    using System.Text;
    using Newtonsoft.Json;

    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        private static readonly object SyncRoot = new object();
        private static readonly string ConfigFilePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "appsettings.json");
        private static readonly SettingsData CurrentData = Load();

        private Settings() {
        }

        public static Settings Default {
            get {
                return ((Settings)(ApplicationSettingsBase.Synchronized(new Settings())));
            }
        }

        public new void Save() {
            lock (SyncRoot) {
                var json = JsonConvert.SerializeObject(CurrentData, Formatting.Indented);
                File.WriteAllText(ConfigFilePath, json, new UTF8Encoding(false));
            }
        }

        private static SettingsData Load() {
            try {
                if (!File.Exists(ConfigFilePath)) {
                    return new SettingsData();
                }

                var json = File.ReadAllText(ConfigFilePath, Encoding.UTF8);
                return JsonConvert.DeserializeObject<SettingsData>(json) ?? new SettingsData();
            }
            catch {
                return new SettingsData();
            }
        }

        private static string GetString(Func<SettingsData, string> getter) {
            lock (SyncRoot) {
                return getter(CurrentData) ?? string.Empty;
            }
        }

        private static void SetString(Action<SettingsData, string> setter, string value) {
            lock (SyncRoot) {
                setter(CurrentData, value ?? string.Empty);
            }
        }

        private static bool GetBool(Func<SettingsData, bool> getter) {
            lock (SyncRoot) {
                return getter(CurrentData);
            }
        }

        private static void SetBool(Action<SettingsData, bool> setter, bool value) {
            lock (SyncRoot) {
                setter(CurrentData, value);
            }
        }

        public string configSaveImageFolder {
            get { return GetString(x => x.configSaveImageFolder); }
            set { SetString((x, v) => x.configSaveImageFolder = v, value); }
        }

        public string configServer {
            get { return GetString(x => x.configServer); }
            set { SetString((x, v) => x.configServer = v, value); }
        }

        public string configDatabase {
            get { return GetString(x => x.configDatabase); }
            set { SetString((x, v) => x.configDatabase = v, value); }
        }

        public bool configPreProd {
            get { return GetBool(x => x.configPreProd); }
            set { SetBool((x, v) => x.configPreProd = v, value); }
        }

        public string configQuerySQL {
            get { return GetString(x => x.configQuerySQL); }
            set { SetString((x, v) => x.configQuerySQL = v, value); }
        }

        public string configSaveCSVFolder {
            get { return GetString(x => x.configSaveCSVFolder); }
            set { SetString((x, v) => x.configSaveCSVFolder = v, value); }
        }

        public string configSaveTripExceptionCSVFolder {
            get { return GetString(x => x.configSaveTripExceptionCSVFolder); }
            set { SetString((x, v) => x.configSaveTripExceptionCSVFolder = v, value); }
        }

        public string configSaveCECFolder {
            get { return GetString(x => x.configSaveCECFolder); }
            set { SetString((x, v) => x.configSaveCECFolder = v, value); }
        }

        public string configAccessKey {
            get { return GetString(x => x.configAccessKey); }
            set { SetString((x, v) => x.configAccessKey = v, value); }
        }

        public string configSecretKey {
            get { return GetString(x => x.configSecretKey); }
            set { SetString((x, v) => x.configSecretKey = v, value); }
        }

        public string configBucketName {
            get { return GetString(x => x.configBucketName); }
            set { SetString((x, v) => x.configBucketName = v, value); }
        }

        public string configQuerySearchCEC {
            get { return GetString(x => x.configQuerySearchCEC); }
            set { SetString((x, v) => x.configQuerySearchCEC = v, value); }
        }

        public string configURLToken {
            get { return GetString(x => x.configURLToken); }
            set { SetString((x, v) => x.configURLToken = v, value); }
        }

        public string configURLSync {
            get { return GetString(x => x.configURLSync); }
            set { SetString((x, v) => x.configURLSync = v, value); }
        }

        public string configLogin {
            get { return GetString(x => x.configLogin); }
            set { SetString((x, v) => x.configLogin = v, value); }
        }

        public string configPassword {
            get { return GetString(x => x.configPassword); }
            set { SetString((x, v) => x.configPassword = v, value); }
        }

        public string configLoginUrl {
            get { return GetString(x => x.configLoginUrl); }
            set { SetString((x, v) => x.configLoginUrl = v, value); }
        }

        public string configLoginSuccessUrl {
            get { return GetString(x => x.configLoginSuccessUrl); }
            set { SetString((x, v) => x.configLoginSuccessUrl = v, value); }
        }

        public string configDomain {
            get { return GetString(x => x.configDomain); }
            set { SetString((x, v) => x.configDomain = v, value); }
        }

        public string configEnvironment {
            get { return GetString(x => x.configEnvironment); }
            set { SetString((x, v) => x.configEnvironment = v, value); }
        }

        public string configValidationRulesPath {
            get { return GetString(x => x.configValidationRulesPath); }
            set { SetString((x, v) => x.configValidationRulesPath = v, value); }
        }

        public string configDbComparisonRulesPath {
            get { return GetString(x => x.configDbComparisonRulesPath); }
            set { SetString((x, v) => x.configDbComparisonRulesPath = v, value); }
        }

        private sealed class SettingsData {
            public string configSaveImageFolder { get; set; } = string.Empty;
            public string configServer { get; set; } = string.Empty;
            public string configDatabase { get; set; } = string.Empty;
            public bool configPreProd { get; set; }
            public string configQuerySQL { get; set; } = string.Empty;
            public string configSaveCSVFolder { get; set; } = string.Empty;
            public string configSaveTripExceptionCSVFolder { get; set; } = string.Empty;
            public string configSaveCECFolder { get; set; } = string.Empty;
            public string configAccessKey { get; set; } = string.Empty;
            public string configSecretKey { get; set; } = string.Empty;
            public string configBucketName { get; set; } = string.Empty;
            public string configQuerySearchCEC { get; set; } = string.Empty;
            public string configURLToken { get; set; } = string.Empty;
            public string configURLSync { get; set; } = string.Empty;
            public string configLogin { get; set; } = string.Empty;
            public string configPassword { get; set; } = string.Empty;
            public string configLoginUrl { get; set; } = string.Empty;
            public string configLoginSuccessUrl { get; set; } = string.Empty;
            public string configDomain { get; set; } = string.Empty;
            public string configEnvironment { get; set; } = string.Empty;
            public string configValidationRulesPath { get; set; } = string.Empty;
            public string configDbComparisonRulesPath { get; set; } = string.Empty;
        }
    }
}
